config/routes.rb
Rails.application.routes.draw do
  devise_for :users           # 認証
  root 'contents#index'       # トップページ
  # root 'static_pages#index'   # トップページ
  resources :sites            # サイトメンテナンス

  # コンテンツ
  get 'contents/(:id)',       to:'contents#index'
  # get 'contents/:id/edit',  to:'contents#edit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :user
  has_many :contents
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sites
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # usernameを追加したことによる対応
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    # usernameを追加したことによる対応
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_sites, only: [:index, :show]
  before_action :authenticate_user!

  # ----------------------------------------
  def index
    # サイト一覧用
    @site_id = params[:id]
    @contents = []

    # サイトが未選択なら戻る
    return if !params[:id]

    # サイト
    site = Site.find(params[:id])

    # rssを追加
    rss = Feedjira::Feed.fetch_and_parse site.url
    rss.entries.each do |item|
      @contents += [
        author: item.author || site.name,
        title: item.title,
        url: item.url,
        summary: item.summary,
        postdt: item.published.to_time.strftime("%Y-%m-%d %H:%M:%S")]
    end
  end # index

  private
    def set_sites
      @sites = Site.all
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
    @site.user_id = current_user.id
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:user_id, :name, :url, :max_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/contents/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <% @sites.each do |site| %>
        <%= link_to({controller: :contents, action: :index, id: site.id}) do %>
          <div class="panel-body">
            <%= site.name %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-9">
      <table class="table table-hover table-striped">
        <tbody>
        <% @contents.each do |content| %>
          <%= link_to(content[:url]) do %>
            <tr data-url="<%=content[:url] %>">
              <td class="author">
                <%= link_to content[:author], content[:url], target: '_blank' %>
              </td>
              <td class="title">
                <%= link_to content[:title], content[:url], target: '_blank' %>
              </td>
              <td class="postdt">
                <%= link_to content[:postdt], content[:url], target: '_blank' %>
              </td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rssr</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav>
        <% if user_signed_in? %>
          <%= link_to 'ホーム', root_path %>
          <%= link_to 'サイト編集', sites_path %>
          <string><%= link_to current_user.username, '#' %></string>
          <%= link_to 'プロフィール変更', edit_user_registration_path %>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to 'サインアップ', new_user_registration_path %>
          <%= link_to 'ログイン', new_user_session_path %>
        <% end %>
      </nav>
    </header>
    <p id="notice" class="notice"><%= notice %></p>
    <p id="alert" class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/sites/_form.html.erb
<%= form_for(site) do |f| %>
  <% if site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :max_count %>
    <%= f.number_field :max_count %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Editing Site</h1>
      
      <%= render 'form', site: @site %>
      
      <%= link_to 'Show', @site %> |
      <%= link_to 'Back', sites_path %>
    </div>
  </div>
</div>

app/views/sites/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Sites</h1>
      
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Url</th>
            <th>Max count</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @sites.each do |site| %>
            <tr>
              <td><%= site.name %></td>
              <td><%= site.url %></td>
              <td><%= site.max_count %></td>
              <td><%= link_to 'Show', site %></td>
              <td><%= link_to 'Edit', edit_site_path(site) %></td>
              <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <br>
      
      <%= link_to 'New Site', new_site_path %>
    </div>
  </div>
</div>

app/views/sites/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>New Site</h1>
      
      <%= render 'form', site: @site %>
      
      <%= link_to 'Back', sites_path %>
    </div>
  </div>
</div>

app/views/sites/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <p>
        <strong>Name:</strong>
        <%= @site.name %>
      </p>
      
      <p>
        <strong>Url:</strong>
        <%= @site.url %>
      </p>
      
      <p>
        <strong>Max count:</strong>
        <%= @site.max_count %>
      </p>
      
      <%= link_to 'Edit', edit_site_path(@site) %> |
      <%= link_to 'Back', sites_path %>
    </div>
  </div>
</div>